// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "amplify-starter-20190327203356-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d1a1dkbvmeyll1.cloudfront.net",
    "aws_cognito_identity_pool_id": "eu-central-1:9baf632a-b162-4c33-a111-690930afa35a",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_70SKlS0d2",
    "aws_user_pools_web_client_id": "6h7gi6e2e8mftrrthp563nrqhv"
};


export default awsmobile;
